import Image from 'next/image';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import ContactForm from '@/components/ContactForm';
import {services,getService} from '@/lib/services';

export const generateStaticParams=()=>services.map(s=>({slug:s.slug}));
export async function generateMetadata({params}){const {slug}=await params,s=getService(slug);return s?{title:slug==='van-chuyen-duong-bien'?'Vận chuyển đường biển quốc tế FCL/LCL':s.name,description:slug==='van-chuyen-duong-bien'?'Báo giá vận chuyển đường biển quốc tế FCL/LCL theo tuyến, lịch tàu, loại hàng và địa điểm giao nhận.':'Dịch vụ '+s.name+' cho doanh nghiệp, tư vấn quy trình và báo giá theo lô hàng.'}:{};}

const faq=[
 ['Phí local charges gồm những khoản nào?','Tùy tuyến và điều kiện giao hàng, báo giá có thể gồm cước biển, phí tại cảng đi/cảng đến, chứng từ, CFS/THC, trucking, thông quan và các phụ phí của hãng tàu. Everest sẽ tách từng nhóm phí trong báo giá để doanh nghiệp đối chiếu.'],
 ['Demurrage và detention khác nhau thế nào?','Demurrage thường liên quan thời gian container nằm trong cảng vượt thời gian miễn phí; detention liên quan thời gian giữ container ngoài cảng. Mức miễn phí và biểu phí phụ thuộc hãng tàu, cảng và booking thực tế.'],
 ['Có nên mua bảo hiểm hàng hóa đường biển không?','Doanh nghiệp nên cân nhắc bảo hiểm dựa trên giá trị, tính chất hàng, điều kiện giao hàng và mức rủi ro của hành trình. Cước vận chuyển không mặc nhiên bao gồm bảo hiểm nếu báo giá không ghi rõ.'],
 ['Everest có nhận hàng nguy hiểm không?','Cần kiểm tra theo từng đơn hàng cụ thể. Doanh nghiệp nên cung cấp tính chất hàng và các thông tin liên quan để Everest xác nhận khả năng vận chuyển.'],
 ['Lịch tàu và transit time có cố định không?','Không. Lịch tàu, chuyến direct hoặc via và transit time được cập nhật theo booking, hãng tàu, cảng và thời điểm. Khoảng tham khảo thường là 5–10 ngày cho một số tuyến châu Á và 30–45 ngày cho một số tuyến châu Âu.']
];
const routes=[
 ['Châu Á','Trung Quốc, Hàn Quốc, Thái Lan, Singapore, Nhật Bản, Philippines, Malaysia, Ấn Độ','Cát Lái, Cái Mép, Hải Phòng, Đà Nẵng, Quy Nhơn và cảng quốc tế theo booking','Khoảng 5–10 ngày, cập nhật theo booking'],
 ['Châu Âu','Đức, Hà Lan, Bỉ, Pháp, Ý, Tây Ban Nha và các điểm đến phù hợp','Hải Phòng/Cát Lái/Cái Mép đến cảng đích theo booking','Khoảng 30–45 ngày, cập nhật theo booking'],
 ['Bắc Mỹ và tuyến khác','Mỹ, Canada, Úc, Dubai và Lào','Cảng đi/cảng đến xác định theo lô hàng và hãng tàu','Cập nhật theo booking']
];

function OtherService({s}){return <main><section className="pageHero"><div className="container"><span className="eyebrow">{s.group}</span><h1>{s.name}</h1><p>Giải pháp theo tuyến vận chuyển, đặc tính hàng hóa và yêu cầu chứng từ thực tế.</p></div></section><section className="section"><div className="container serviceLayout"><article className="content"><Image className="servicePhoto" src={'/images/'+s.image} alt={s.name} width={900} height={520}/><h2>Dịch vụ {s.name.toLowerCase()}</h2><p className="lead">Everest tiếp nhận thông tin, kiểm tra điều kiện và đề xuất phương án rõ về phạm vi, lịch trình và chi phí.</p><h2>Phạm vi hỗ trợ</h2><ul><li>Khảo sát nhu cầu và kiểm tra thông tin lô hàng</li><li>Tư vấn quy trình, chứng từ và mốc tiến độ</li><li>Điều phối thực hiện với một đầu mối</li><li>Cập nhật trạng thái và xử lý phát sinh</li><li>Bàn giao hồ sơ và đối soát</li></ul></article><ContactForm compact service={s.name}/></div></section></main>}

export default async function ServicePage({params}){
 const {slug}=await params,s=getService(slug);if(!s)notFound();if(slug!=='van-chuyen-duong-bien')return <OtherService s={s}/>;
 const schema={'@context':'https://schema.org','@type':'Service',name:'Vận chuyển đường biển quốc tế FCL/LCL',serviceType:'International sea freight',url:'https://everlog.com.vn/dich-vu/van-chuyen-duong-bien',provider:{'@type':'Organization',name:'Công ty TNHH Everest Logistics',url:'https://everlog.com.vn'}};
 return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="pageHero"><div className="container"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Trang chủ</Link><span> / </span><Link href="/dich-vu">Dịch vụ</Link><span> / Vận chuyển đường biển</span></nav><span className="eyebrow">Vận chuyển quốc tế · FCL / LCL</span><h1>Vận chuyển đường biển quốc tế</h1><p>Báo giá FCL/LCL theo tuyến, lịch tàu, loại hàng và điểm lấy – giao. Phạm vi có thể kết hợp door-to-door, sea-air, hàng quá khổ và tracking.</p><div className="actions"><a className="btn btnOrange" href="#bao-gia">Nhận báo giá FCL/LCL</a><a className="btn" href="#lich-tau">Xem tuyến và lịch tàu</a></div></div></section>
 <section className="section sectionAlt"><div className="container"><div className="sectionHead"><span className="eyebrow">Chọn phương án trước khi nhận giá</span><h2>Ba cách triển khai cho lô hàng</h2></div><div className="grid serviceChoice"><article className="card"><h3>FCL · Hàng nguyên container</h3><p>Dành cho lô hàng đủ đóng container 20’ khoảng 30 CBM hoặc container 40’ khoảng 70 CBM.</p><a href="#so-sanh">Xem điều kiện FCL →</a></article><article className="card"><h3>LCL · Hàng lẻ</h3><p>Phù hợp với lô hàng dưới 10 tấn và nhỏ hơn 15 CBM. Cước thường đối chiếu theo RT hoặc CBM tùy báo giá.</p><a href="#so-sanh">Xem điều kiện LCL →</a></article><article className="card"><h3>Door-to-door và sea-air</h3><p>Giao hàng door-to-door hoặc kết hợp đường biển – đường hàng không theo từng nhu cầu của doanh nghiệp.</p><a href="#quy-trinh">Xem quy trình →</a></article></div><div id="bao-gia" className="quoteLead"><div><span className="eyebrow">Báo giá theo lô hàng</span><h2>Gửi thông tin để nhận phương án FCL/LCL</h2><p>Thông tin càng đầy đủ, báo giá càng sát với tuyến, loại container, local charges và thời gian dự kiến.</p></div><ContactForm compact service="Vận chuyển đường biển"/></div></div></section>
 <section className="section"><div className="container content"><h2 id="so-sanh">So sánh FCL và LCL</h2><div className="tableWrap"><table><thead><tr><th>Tiêu chí</th><th>FCL</th><th>LCL</th></tr></thead><tbody><tr><th>Khi dùng</th><td>Lô hàng đủ lớn hoặc cần dùng riêng container.</td><td>Lô hàng nhỏ, ghép cùng các lô khác qua CFS.</td></tr><tr><th>Đơn vị tính</th><td>Theo container và loại container.</td><td>Thường theo RT/W-M: so sánh trọng lượng tấn và thể tích CBM, lấy số lớn hơn; áp dụng theo báo giá.</td></tr><tr><th>Thời gian</th><td>Thường ít khâu gom hàng hơn; phụ thuộc cut-off, chuyến tàu và cảng.</td><td>Thêm thời gian đưa hàng vào/ra CFS và xử lý gom, tách hàng.</td></tr><tr><th>Ưu điểm</th><td>Chủ động đóng hàng, ít thao tác chia tách, phù hợp lô lớn.</td><td>Không phải trả nguyên container; phù hợp sản lượng nhỏ.</td></tr><tr><th>Hạn chế</th><td>Chi phí container có thể không tối ưu nếu hàng ít.</td><td>Có thêm phí CFS và phụ thuộc lịch gom/tách hàng.</td></tr></tbody></table></div><blockquote>Đừng chọn FCL chỉ vì nhìn thấy đơn giá container thấp. Hãy đối chiếu sản lượng thực tế, loại hàng, phí tại CFS và chi phí lưu container trước khi chốt phương án.</blockquote></div></section>
 <section id="lich-tau" className="section sectionAlt"><div className="container content"><h2>Tuyến chính, cảng đi – cảng đến và transit time</h2><p>Các tuyến dưới đây là phạm vi đang cung cấp theo thông tin dịch vụ. Cảng cụ thể, chuyến direct/via, lịch tàu và transit time được xác nhận lại theo booking; không mặc định là lịch cố định.</p><div className="tableWrap"><table><thead><tr><th>Khu vực</th><th>Tuyến/điểm đến</th><th>Cảng đi tham khảo</th><th>Lịch và transit time</th></tr></thead><tbody>{routes.map(r=><tr key={r[0]}><th>{r[0]}</th><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td></tr>)}</tbody></table></div><p className="muted">Hàng quá khổ, hàng quá tải, tàu rời và Ro-Ro cần kiểm tra riêng theo từng đơn hàng cụ thể.</p></div></section>
 <section id="quy-trinh" className="section"><div className="container"><div className="sectionHead"><span className="eyebrow">Từ hồ sơ đến bàn giao</span><h2>Quy trình 5 bước</h2></div><ol className="steps"><li><strong>Nhận yêu cầu</strong><span>Tiếp nhận tuyến, hàng hóa, sản lượng, thời gian và điều kiện giao hàng.</span></li><li><strong>Tư vấn phương án</strong><span>Đối chiếu FCL/LCL, loại container, lịch tàu, local charges và yêu cầu chuyên ngành.</span></li><li><strong>Booking</strong><span>Xác nhận phương án, cut-off, chứng từ cần nộp và đặt chỗ theo booking.</span></li><li><strong>Chứng từ và thông quan</strong><span>Phối hợp invoice, packing list, B/L, HS, C/O, giấy phép hoặc kiểm tra chuyên ngành nếu có.</span></li><li><strong>Giao hàng và tracking</strong><span>Cập nhật trạng thái, phối hợp giao nhận đầu cuối và xử lý phát sinh theo phạm vi đã thống nhất.</span></li></ol></div></section>
 <section className="section"><div className="container content"><h2>Câu hỏi thường gặp</h2>{faq.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
 <section className="section sectionAlt"><div className="container content checklist"><h2>Doanh nghiệp cần cung cấp gì để báo giá?</h2><ul><li><strong>Tuyến:</strong> POL/POD hoặc địa chỉ lấy hàng và giao hàng.</li><li><strong>Điều kiện thương mại:</strong> Incoterms nếu đã có, ví dụ EXW, FOB, CIF hoặc DDP.</li><li><strong>Hàng hóa:</strong> commodity, HS Code nếu có, hàng thường/lạnh/nguy hiểm/quá khổ.</li><li><strong>Số liệu:</strong> gross weight, CBM, số kiện, kích thước kiện và loại container mong muốn.</li><li><strong>Thời gian:</strong> cargo ready date, cut-off dự kiến và yêu cầu giao hàng.</li></ul></div></section>
 <section className="section sectionAlt"><div className="container cta"><div><span className="eyebrow">Cần chốt tuyến hoặc lịch tàu?</span><h2>Gửi checklist lô hàng để nhận tư vấn</h2><p>Everest sẽ phản hồi theo thông tin booking và phạm vi dịch vụ thực tế.</p></div><a className="btn btnOrange" href="#bao-gia">Nhận báo giá</a></div></section></main>;
}
